### ISSUE TITLE
some items failed

### ISSUE THREAD

**Issue by elypter** [omarroth/archive#4]
no idea why but some items in the beginning of the batch failed

`(node:10616) UnhandledPromiseRejectionWarning: RequestError: Error: socket hang up
    at new RequestError (/home/niemand/archive/node/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/niemand/archive/node/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/niemand/archive/node/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/niemand/archive/node/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/niemand/archive/node/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
(node:10616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 170)
`
i hope this doesnt lead to incomplete data

**Comment by omarroth** [comment]
It should work fine. If you keep getting those errors, I'd suggest lowering the `annotationConcurrentLimit` in `node/worker/config.json`, as I expect the issue is that your connection is not fast enough to support the number of threads.

The server also has some ability to catch incomplete data, so any incomplete work should be rejected.

**Comment by elypter** [comment]
might also just be cache thrashing. its an old computer. the copper line is also just 8mbit download but i assume the limiting factor is still youtube

**Comment by cloudrac3r** [comment]
Dealt with in #7
